### ISSUE TITLE
Issues during install due to WANDB

### ISSUE THREAD

**Issue by mikel-brostrom** [roboflow/rf-detr#77]
### Search before asking

- [x] I have searched the RF-DETR issues and found no similar bug report.

### Bug

It is weird that WANDB is used what so ever during inference, IMO. Anyways,
Could you provide the exact WANDB version that is compatible with RFDETR?

```bash
  File "/home/runner/work/boxmot/boxmot/tracking/detectors/rfdetr.py", line 7, in <module>
    from rfdetr import RFDETRBase
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/rfdetr/__init__.py", line 5, in <module>
    from rfdetr.detr import RFDETRBase, RFDETRLarge
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/rfdetr/detr.py", line 5, in <module>
    from rfdetr.main import Model, download_pretrain_weights
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/rfdetr/main.py", line 32, in <module>
    from rfdetr.datasets import build_dataset, get_coco_api_from_dataset
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/rfdetr/datasets/__init__.py", line 16, in <module>
    from .coco import build as build_coco
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/rfdetr/datasets/coco.py", line 24, in <module>
    import rfdetr.datasets.transforms as T
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/rfdetr/datasets/transforms.py", line 31, in <module>
    from rfdetr.util.misc import interpolate
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/rfdetr/util/misc.py", line 26, in <module>
    import wandb
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/wandb/__init__.py", line 21, in <module>
    from wandb import sdk as wandb_sdk
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/wandb/sdk/__init__.py", line 24, in <module>
    from . import wandb_helper as helper
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/wandb/sdk/wandb_helper.py", line 6, in <module>
    from .lib import config_util
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/wandb/sdk/lib/__init__.py", line 2, in <module>
    from .disabled import RunDisabled, SummaryDisabled
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/wandb/sdk/lib/disabled.py", line 3, in <module>
    from wandb.sdk.lib import deprecate
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/wandb/sdk/lib/deprecate.py", line 7, in <module>
    from wandb.proto.wandb_telemetry_pb2 import Deprecated as TelemetryDeprecated
ImportError: cannot import name 'Deprecated' from 'wandb.proto.wandb_telemetry_pb2' (/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/wandb/proto/wandb_telemetry_pb2.py)
```

### Environment

RF-DETR: 1.0.8
OS: masOC Sequoia 15.1
Python: 3.11

### Minimal Reproducible Example

pip install rfdetr

### Are you willing to submit a PR?

- [ ] Yes, I'd like to help by submitting a PR!

**Comment by SkalskiP** [comment]
@mikel-brostrom Thanks for the report — and yes, you're absolutely right, it's weird that W&B is used during inference. The RF-DETR codebase was originally released in a bit of a hurry, and as a result, there are still some rough edges like this. We're actively working on cleaning things up, and specifically addressing this issue in [PR #70](https://github.com/roboflow/rf-detr/pull/70), where we’re removing the unnecessary W&B dependency from the inference path.

In the meantime, could you let us know which version of wandb you currently have installed? I just set up a clean environment locally on macOS Sequoia 15.1 with Python 3.11 and `rfdetr==1.0.8`, and inference works fine using the latest `wandb==0.19.8`.

As a quick workaround, try upgrading W&B:

```
pip install --upgrade wandb
```

Let us know which version you're using and we'll help troubleshoot further.

**Comment by guyver30** [comment]
Hi
I setup a venv in Ubuntu with python 3.10.12, rf-detr, supervision, inference, jupyter notebook. See attached requirement.txt
When executing the code

import io
import requests
import supervision as sv
from PIL import Image
from rfdetr import RFDETRBase
from rfdetr.util.coco_classes import COCO_CLASSES

model = RFDETRBase()

I get an error
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[1], line 5
      3 import supervision as sv
      4 from PIL import Image
----> 5 from rfdetr import RFDETRBase
      6 from rfdetr.util.coco_classes import COCO_CLASSES
      8 model = RFDETRBase()

File ~/Downloads/rf-detr/rf-detr_venv/lib/python3.10/site-packages/rfdetr/__init__.py:5
      2 if os.environ.get("PYTORCH_ENABLE_MPS_FALLBACK") is None:
      3     os.environ["PYTORCH_ENABLE_MPS_FALLBACK"] = "1"
----> 5 from rfdetr.detr import RFDETRBase, RFDETRLarge

File ~/Downloads/rf-detr/rf-detr_venv/lib/python3.10/site-packages/rfdetr/detr.py:5
      2 import json
      4 from rfdetr.config import RFDETRBaseConfig, RFDETRLargeConfig, TrainConfig, ModelConfig
----> 5 from rfdetr.main import Model, download_pretrain_weights
      6 from functools import partial
      7 from logging import getLogger

File ~/Downloads/rf-detr/rf-detr_venv/lib/python3.10/site-packages/rfdetr/main.py:32
     29 import torch
     30 from torch.utils.data import DataLoader, DistributedSampler
---> 32 from rfdetr.datasets import build_dataset, get_coco_api_from_dataset
     33 from rfdetr.engine import evaluate, train_one_epoch
     34 from rfdetr.models import build_model, build_criterion_and_postprocessors

File ~/Downloads/rf-detr/rf-detr_venv/lib/python3.10/site-packages/rfdetr/datasets/__init__.py:16
     13 import torch.utils.data
     14 import torchvision
---> 16 from .coco import build as build_coco
     17 from .o365 import build_o365
     18 from .coco import build_roboflow

File ~/Downloads/rf-detr/rf-detr_venv/lib/python3.10/site-packages/rfdetr/datasets/coco.py:24
     21 import torch.utils.data
     22 import torchvision
---> 24 import rfdetr.datasets.transforms as T
     27 def compute_multi_scale_scales(resolution, expanded_scales=False):
     28     if resolution == 640:
     29         # assume we're doing the original 640x640 and therefore patch_size is 16

File ~/Downloads/rf-detr/rf-detr_venv/lib/python3.10/site-packages/rfdetr/datasets/transforms.py:31
     28 import torchvision.transforms.functional as F
     30 from rfdetr.util.box_ops import box_xyxy_to_cxcywh
---> 31 from rfdetr.util.misc import interpolate
     34 def crop(image, target, region):
     35     cropped_image = F.crop(image, *region)

File ~/Downloads/rf-detr/rf-detr_venv/lib/python3.10/site-packages/rfdetr/util/misc.py:26
     24 import pickle
     25 from typing import Optional, List
---> 26 import wandb
     27 import copy
     28 import argparse

File ~/Downloads/rf-detr/rf-detr_venv/lib/python3.10/site-packages/wandb/__init__.py:21
     18 # This needs to be early as other modules call it.
     19 from wandb.errors.term import termsetup, termlog, termerror, termwarn
---> 21 from wandb import sdk as wandb_sdk
     23 import wandb
     25 wandb.wandb_lib = wandb_sdk.lib  # type: ignore

File ~/Downloads/rf-detr/rf-detr_venv/lib/python3.10/site-packages/wandb/sdk/__init__.py:25
      3 __all__ = (
      4     "Config",
      5     "Settings",
   (...)
     21     "helper",
     22 )
     24 from . import wandb_helper as helper
---> 25 from .artifacts.artifact import Artifact
     26 from .wandb_alerts import AlertLevel
     27 from .wandb_config import Config

File ~/Downloads/rf-detr/rf-detr_venv/lib/python3.10/site-packages/wandb/sdk/artifacts/artifact.py:40
     38 import wandb
     39 from wandb import data_types, env, util
---> 40 from wandb.apis.normalize import normalize_exceptions
     41 from wandb.apis.public import ArtifactCollection, ArtifactFiles, RetryingClient, Run
     42 from wandb.data_types import WBValue

File ~/Downloads/rf-detr/rf-detr_venv/lib/python3.10/site-packages/wandb/apis/__init__.py:44
     41 reset_path = util.vendor_setup()
     43 from .internal import Api as InternalApi  # noqa
---> 44 from .public import Api as PublicApi  # noqa
     46 reset_path()
     48 __all__ = ["InternalApi", "PublicApi"]

File ~/Downloads/rf-detr/rf-detr_venv/lib/python3.10/site-packages/wandb/apis/public/__init__.py:1
----> 1 from wandb.apis.public.api import Api, RetryingClient, requests
      2 from wandb.apis.public.artifacts import (
      3     ARTIFACT_FILES_FRAGMENT,
      4     ARTIFACTS_TYPES_FRAGMENT,
   (...)
     11     RunArtifacts,
     12 )
     13 from wandb.apis.public.files import FILE_FRAGMENT, File, Files

File ~/Downloads/rf-detr/rf-detr_venv/lib/python3.10/site-packages/wandb/apis/public/api.py:28
     26 from wandb.apis import public
     27 from wandb.apis.normalize import normalize_exceptions
---> 28 from wandb.apis.public._generated import SERVER_FEATURES_QUERY_GQL, ServerFeaturesQuery
     29 from wandb.apis.public.const import RETRY_TIMEDELTA
     30 from wandb.apis.public.registries import Registries

File ~/Downloads/rf-detr/rf-detr_venv/lib/python3.10/site-packages/wandb/apis/public/_generated/__init__.py:3
      1 # Generated by ariadne-codegen
----> 3 from .base import Base, GQLBase, GQLId, SerializedToJson, Typename
      4 from .operations import SERVER_FEATURES_QUERY_GQL
      5 from .server_features_query import (
      6     ServerFeaturesQuery,
      7     ServerFeaturesQueryServerInfo,
      8     ServerFeaturesQueryServerInfoFeatures,
      9 )

File ~/Downloads/rf-detr/rf-detr_venv/lib/python3.10/site-packages/wandb/apis/public/_generated/base.py:9
      7 from pydantic import BaseModel, ConfigDict, Field, Json, ValidationError, WrapValidator
      8 from pydantic.alias_generators import to_camel
----> 9 from pydantic.main import IncEx
     10 from pydantic_core import to_json
     11 from pydantic_core.core_schema import ValidatorFunctionWrapHandler

ImportError: cannot import name 'IncEx' from 'pydantic.main' (/home/dario/Downloads/rf-detr/rf-detr_venv/lib/python3.10/site-packages/pydantic/main.py)

[requirement.txt](https://github.com/user-attachments/files/19546647/requirement.txt)

**Comment by SkalskiP** [comment]
Thanks for the detailed report, @guyver30!

This looks like a separate issue from the one originally reported by @mikel-brostrom. Based on the traceback, it seems there's an incompatibility between the `wandb` version you're using (`0.19.8`, which is correct) and the version of `pydantic` in your environment (`2.6.4`).

To resolve this, you can try upgrading `pydantic` to the latest version:

```bash
pip install --upgrade pydantic
```

Alternatively, we’ve just merged [#70](https://github.com/roboflow/rf-detr/pull/70), which removes the unnecessary `wandb` dependency from the inference path altogether — helping avoid these kinds of issues going forward.

That update hasn't been released yet in PyPI, but you can test it right away by installing RF-DETR from source:

```bash
pip install git+https://github.com/roboflow/rf-detr.git
```

Let us know if this resolves the issue!

**Comment by SkalskiP** [comment]
RF-DETR v1.1.0 treats `wandb` as an optional dependency. I'm closing this issue. Feel free to reopen it if you encounter similar problems.
