### PR TITLE
RFDETR-Seg ONNX Export Failing

### PR DESCRIPTION
**Pull request by taharh**
## What does this PR do?

Fixes ONNX export for segmentation models.

**Issues fixed:**

1. Export failed with `AttributeError: 'dict' object has no attribute 'shape'` because `pred_masks` can be a dictionary (containing `spatial_features`, `query_features`, `bias`) rather than a tensor. Added a check to handle both cases in `main.py` and `deploy/export.py`.

2. Pinned `onnx>=1.16.0,<1.20` in `pyproject.toml` to avoid compatibility issues with `onnx_graphsurgeon` (onnx 1.20+ removed `float32_to_bfloat16`).

**Related Issue(s):**  Related to PR #578 and to Issue #580 

## Type of Change

- Bug fix (non-breaking change that fixes an issue)

## Testing

- [x] I have tested this change locally

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code where necessary, particularly in hard-to-understand areas
- [x] My changes generate no new warnings or errors
- [ ] I have updated the documentation accordingly (if applicable)

### CODE REVIEW

**Comment by probicheaux** [comment]
lgtm!

**Review by probicheaux — DISMISSED** [review]

File: tests/util/test_export_segmentation.py [hunk 1]
```diff
@@ -0,0 +1,62 @@
...
+    def test_segmentation_model_export_no_crash(self, output_dir):
+        """
+        Test that exporting a segmentation model does not crash.
+
+        This is the actual integration test that exercises the full export path.
+        """
+        try:
+            from rfdetr import RFDETRSegNano
+        except ImportError:
+            pytest.skip("rfdetr not installed")
```
Comment (Borda) [inline tests/util/test_export_segmentation.py]:
```suggestion
```
what is the case this is missing?

File: tests/util/test_export_segmentation.py [hunk 2]
```diff
@@ -0,0 +1,62 @@
...
+
+        try:
+            import onnx  # noqa: F401
+        except ImportError:
+            pytest.skip("onnx not installed, run: pip install rfdetr[onnxexport]")
```
Comment (Borda) [inline tests/util/test_export_segmentation.py]: Use rather a decorator `pytest.mark.skipif(...)`

File: pyproject.toml [hunk 3]
```diff
@@ -54,7 +54,7 @@ dependencies = [
 
 [project.optional-dependencies]
 onnxexport = [
-    "onnx",
+    "onnx>=1.16.0,<1.20",
```
Comment (Borda) [inline pyproject.toml:58]:
```suggestion
    "onnx>=1.16.0",
```
Won't it work with versions above 1.20?

Comment (taharh) [reply pyproject.toml:58]: No as it will throw a 'AttributeError: module 'onnx.helper' has no attribute 'float32_to_bfloat16''

For reference:
- [Issue 580](https://github.com/roboflow/rf-detr/issues/580)
